[project]
name = "tibava-interface"
version = "0.1.0"
description = "Interface class and definition for tibava"
readme = "README.md"
authors = [
    { name = "matthias springstein", email = "matthias.springstein@protonmail.com" },
]
requires-python = ">=3.12"
dependencies = ["grpcio>=1.70.0", "protobuf>=5.29.3"]

[tool.uv]
package = true
